name: Tests

on:
  push:
    branches: [main]

jobs:
  directories:
    runs-on: ubuntu-latest

    outputs:
      dirs: ${{ steps.get-dirs.outputs.directories }}

    steps:
      - uses: actions/checkout@v3

      - name: Determine working directories
        id: get-dirs
        uses: secondtruth/collect-directories-by-contained-files@v1.0.0
        with:
          files-glob: 'flamecore-*/phpunit.xml.dist'

  phpunit-tests:
    runs-on: ubuntu-latest

    needs: [directories]

    strategy:
      matrix:
        dir: ${{ fromJson(needs.directories.outputs.dirs) }}
        php-versions: ['8.0', '8.1']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, iconv, intl, pdo_sqlite
          tools: phpunit:9.5

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install -n --prefer-dist
        working-directory: ${{ matrix.dir }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: PHPUnit Tests
        run: phpunit --coverage-text --coverage-clover=coverage.clover
        working-directory: ${{ matrix.dir }}
